-
  branches:
    only:
      - master

  image: Visual Studio 2022
  version: 4.11.0-master-build.{build}
  configuration: Release

  skip_commits:
    files:
      - docs/*

  before_build:
    - dotnet restore

  build:
    verbosity: minimal

  artifacts:
    - path: '**\*.nupkg'

  deploy:
    provider: NuGet
    api_key:
      secure: DCeHUu0aAsOjRnoi2DpcuXpj0apD7dxHzglSamP7LGzcZjhIvTBi1ONnjIa7L2zm
    skip_symbols: false
    artifact: /.*\.nupkg/

-
  branches:
    only:
      - development

  image: Visual Studio 2022
  version: 5.0.0-dev-build.{build}
  configuration: Release

  skip_commits:
    files:
      - docs/*

  before_build:
    - dotnet restore

  build:
    verbosity: minimal

  artifacts:
    - path: '**\*.nupkg'
