-
  branches:
    only:
      - master

  image: Visual Studio 2022
  version: 5.4.0-master-build.{build}
  configuration: Release

  skip_commits:
    files:
      - docs/*

  before_build:
    - dotnet restore

  build:
    verbosity: minimal

  artifacts:
    - path: '**\*.nupkg'

  deploy:
    provider: NuGet
    api_key:
      secure: orcP0C1iuBVKxnv/uAUehgU1KEI/lCpbSxDqbckd3sZ7XxcuENj6PrExs6SdJIf1
    skip_symbols: false
    artifact: /.*\.nupkg/

-
  branches:
    only:
      - development

  image: Visual Studio 2022
  version: 5.4.0-dev-build.{build}
  configuration: Release

  skip_commits:
    files:
      - docs/*

  before_build:
    - dotnet restore

  build:
    verbosity: minimal

  artifacts:
    - path: '**\*.nupkg'
