name: 🔒Reusable Workflow Build for Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        description: 'The operating system to use'
      image:
        required: true
        type: string
        description: 'The image to use'
      architecture:
        required: true
        type: string
        description: 'The architecture to use'
      build_configuration:
        required: true
        type: string
        description: 'The build configuration to use'

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Upload Test Build Output Cache
    runs-on: ${{inputs.image}}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Build
        run: |
          dotnet restore AsmResolver.sln;
          # msbuild AsmResolver.sln -t:restore -p:RestorePackagesConfig=true
          msbuild AsmResolver.sln -property:Configuration=${{inputs.build_configuration}} -property:Platform=${{inputs.architecture}};

      - name: Upload Build Artifacts
        uses: ./.github/actions/test-build-artifacts-upload
        with:
          image: ${{inputs.image}}
          architecture: ${{inputs.architecture}}
          build_configuration: ${{inputs.build_configuration}}

      - name: Upload Build Cache
        uses: ./.github/actions/test-build-cache-upload
        with:
          image: ${{inputs.image}}
          architecture: ${{inputs.architecture}}
          build_configuration: ${{inputs.build_configuration}}